### ISSUE TITLE
PEP8 적용

### ISSUE THREAD

**Issue by visionNoob** [DeepBaksuVision/YOLO9000#19]
이번 프로젝트에도 PEP8 적용 관련 스크립트가 추가되면 좋을 것 같습니다.

**Comment by ssaru** [comment]
그거는 제가 담당해서 진행하겠습니다.

**Comment by ssaru** [comment]
- python 버전은 3.6으로 고정하기

- mypy 사용하기.
http://mypy-lang.org/
https://item4.github.io/2017-09-14/Python-Typing-with-mypy/

- python makefile 알아보기
https://github.com/kkweon/icarebot/blob/master/Makefile
https://krzysztofzuraw.com/blog/2016/makefiles-in-python-projects.html

- pytest 알아보기
https://twpower.github.io/15-install-pytest-and-basic-usage

- doctest 알아보기
https://python-guide-kr.readthedocs.io/ko/latest/writing/tests.html

- pytest --cov 옵션 알아보기
특정 폴더의 코드를 coverage 대상으로 지정

- isort 알아보기
import 순서 정리
https://pypi.org/project/isort/

- black 알아보기
코드 정리
https://github.com/ambv/black
https://black.readthedocs.io/en/stable/

- pylint 알아보기
https://github.com/kkweon/icarebot/blob/master/.pylintrc

- 개발환경 고정
virtualenv

- pipreqs 알아보기
requirements.txt 자동 생성
https://github.com/bndr/pipreqs

- software test 종류
https://angel927.tistory.com/77

- 오픈소스 컨트리뷰트 문서
https://naver.github.io/OpenSourceGuide/book/BetterContribution/why-contribute-to-open-source.html#beforecontribute
