### ISSUE TITLE
Survey for Python coding convention Cheat-sheet

### ISSUE THREAD

**Issue by visionNoob** [DeepBaksuVision/YOLO9000#3]

**Comment by visionNoob** [comment]
## 1. [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) 
## 2. [The Hitchiker's Guide to PyTorch](https://github.com/Kaixhin/grokking-pytorch)

**Comment by ssaru** [comment]
## Doc String check & Class naming check
https://gist.github.com/RichardBronosky/454964087739a449da04

## PEP 8 -- Style Guid for Python code
https://www.python.org/dev/peps/pep-0008/

## Some Example Good Code Style
https://docs.python-guide.org/writing/style/

**Comment by ssaru** [comment]
## PEP8 Error Code
https://martin-thoma.com/python-style-guide/

**Comment by ssaru** [comment]
## 코드 분석 패키지
`mypy`
`pylint `
`pytest`
`coverage`

## 포매팅
`black`
`isort`

## 설명
pytest-cov 가 파이테스트 커버리지툴로 사용하고
black은 파이썬 코드 포매팅 cli앱이고 yapf은 거의 은퇴하구요. 
isort은 import 순서 정리해주는 cli앱입니다
