### ISSUE TITLE
yolo9000 paper 내용 

### ISSUE THREAD

**Issue by visionNoob** [DeepBaksuVision/YOLO9000#6]
`
We also shrink the network to operate on 416 input images instead of 448×448. We do this because we want an odd number of locations in our feature map so there is a single center cell. Objects, especially large objects, tend to occupy the center of the image so it’s good to have a single location right at the center to predict these objects instead of four locations that are all nearby. YOLO’s convolutional layers downsample the image by a factor of 32 so by using an input image of 416 we get an output feature map of 13 × 13
`

여기에서 
>we want an odd number of locations in our feature map
이 어떤 의미 인가요?

**Comment by visionNoob** [comment]
단순히 결과 matrix의 center 가 네 개가 아닌 딱 하나가 되도록 함이 주 목적일까요?

**Comment by ssaru** [comment]
예를들어 최종 feature map이 7x7이라고 가정했을 때,
큰 Object의 경우(Image 전체를 차지할 정도로) 대부분의 label의 center point가 이미지 중앙에 옵니다.
(width / 2, height/2)

input image가 448x448인 경우 scale factor에 의해 feature map이 down sclae되었을 때, 짝수범위로 나타나 feature map의 center 인근에는 4개의 classifier cell이 존재하게됩니다.

하지만 input image가 416x416인 경우 feature map의 center 부근에 정확하게 딱 1개의 classifier cell이 존재해서 큰 Object에 대해서는 center classifier cell이 이를 모두 담당하게 됩니다.

**Comment by ssaru** [comment]
@insurgent92 네 맞습니다. 4개의 cell로 분산되었을 때의 성능과 1개의 cell에 집중되었을 때에 네트워크에 영향이 어떻게 가는지에 대한 실험내용은 없어서 어떤 의미가 있는지는 잘 모르겠습니다.

**Comment by visionNoob** [comment]
@ssaru 그러게요! 단순하게 생각하면 4개더라도 NMS를 하면 동일하지 않을까 싶기두 하구요! 
수요일 회의때 다시한번 논의해보도록 하죠!
